SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') as DATE_FORMAT
from MEMBER_PROFILE
where DATE_OF_BIRTH like '%-03-%' and GENDER = 'W' and TLNO IS NOT NULL
order by MEMBER_ID;